import { Column, Entity, PrimaryColumn } from 'typeorm';
import type { CertificatePayload } from './certificate-signing';

// One ISSUED Certificate of Data Erasure (plan step 29), stored once and
// never changed: the table rejects UPDATE, DELETE and TRUNCATE at a trigger
// (migration 1752670000000-CreateErasureCertificates). A re-wipe issues a NEW
// row; it never edits an old one. Only written when CERT_SIGNING_KEY is set -
// see certificate-signing.ts and certificate-ledger.ts.
//
// Not in the "powersync" publication and not in the sync rules: nothing
// offline reads certificates, and the payload holds drive serials and names.
@Entity('erasure_certificates')
export class ErasureCertificate {
  // Random (v4), generated by the API so it can be part of the signed
  // payload; it is also the public check's URL, so it must not be guessable.
  @PrimaryColumn('uuid')
  id: string;

  // Issue order, and the chain head is the highest. Assigned by Postgres
  // (GENERATED ALWAYS AS IDENTITY), never written by the API.
  @Column({ type: 'bigint', insert: false, update: false })
  seq: string;

  // The human-readable certificate number printed on the PDF.
  @Column({ type: 'text', unique: true })
  number: string;

  // No foreign key on purpose: an issued certificate outlives the asset row
  // (deleting an asset must neither delete its certificates - the trigger
  // would refuse, and the delete with it - nor be blocked by them).
  @Column({ name: 'asset_id', type: 'uuid' })
  assetId: string;

  // The snapshot the PDF is drawn from, exactly as hashed and signed.
  @Column({ type: 'jsonb' })
  payload: CertificatePayload;

  @Column({ name: 'payload_sha256', type: 'char', length: 64 })
  payloadSha256: string;

  // The previous certificate's payload_sha256; NULL only on the first.
  @Column({ name: 'prev_sha256', type: 'char', length: 64, nullable: true })
  prevSha256: string | null;

  // Ed25519 over the canonical payload, base64.
  @Column({ type: 'text' })
  signature: string;

  @Column({ name: 'key_id', type: 'varchar', length: 16 })
  keyId: string;

  @Column({ name: 'issued_at', type: 'timestamptz' })
  issuedAt: Date;
}
